model {
  file: "model.sdf"
}
name: "Threshold_Textured_Damask_Bath_Towel_Pink"
description: "Threshold Textured Damask Bath Towel - Pink"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Threshold"
}
annotations {
  key: "gtin"
  value: "00042075385644"
}
annotations {
  key: "sku"
  value: "00042075385644"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
